[tool.poetry]
name = "python-travel-api"
version = "0.1.0"
description = ""
authors = ["rbides <renanbides@gmail.com>"]
readme = "README.md"
package-mode = false # Fixing a dependency build. Do we need this?

[tool.poetry.dependencies]
python = "3.10.12"
fastapi = "^0.115.0"
uvicorn = "^0.31.0"
sqlalchemy = "^2.0.35"
pydantic-settings = "^2.5.2"
python-dotenv = "^1.0.1"
alembic = "^1.13.3"
psycopg2-binary = "^2.9.9"
pytest = "^8.3.3"
python-multipart = "^0.0.19"
pyjwt = {extras = ["crypto"], version = "^2.10.1"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
bcrypt = "4.0.1"
sqladmin = "^0.20.1"
itsdangerous = "^2.2.0"
black = "^24.10.0"
pre-commit = "^4.0.1"
flake8 = "^7.1.1"
isort = "^5.13.2"

[tool.black]
line-length = 79
exclude = '''
    /(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    )/
'''

[tool.isort]  
skip = ["__init__.py"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
